import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProvider";
import ApolloProvider from "@/providers/apolloProvider";
import NavBar from "@/common/components/organisms/NavBar";
import SessionProvider from "@/providers/sessionProvider";
import AuthProvider from "@/providers/AuthProvider";
import ToasterProvider from "@/providers/reactHotToast-Provider";
import ReduxProvider from "@/providers/reduxProvider";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReduxProvider>
					<SessionProvider>
						<AuthProvider>
							<ApolloProvider>
								<ThemeProvider
									attribute="class"
									defaultTheme="system"
									enableSystem
									disableTransitionOnChange
								>
									<ToasterProvider />
									<NavBar />
									{children}
								</ThemeProvider>{" "}
							</ApolloProvider>
						</AuthProvider>
					</SessionProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
